version: "3.4"

services:
  app:
    build: ./Application
    image: jtinder-image
    container_name: jtinder
    networks:
      - cloud
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  client:
        build: ./Client
        image: client-image
        container_name: client
        networks:
          - cloud
        ports:
          - 8081:8081
  db:
    image: postgres:latest
    container_name: db
    networks:
      - cloud
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  cloud:
    external: true
