
### Регистрация, после выведет пользователя с зашифрованным паролем,
POST http://localhost:8080/registration
Content-Type: application/json

{
  "userId"  :  13,
  "username" : "Lesha",
  "password" : "Alexey"
}

### Логин, не забудь скопировать полученный токен без кавычек
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "11",
  "password" : "password"
}

### После лгина вставить токен после слова "Bearer" и получить привет с именем текущего пользователя
POST http://localhost:8080/home
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### Текущий подьзователь ставит лайк Арсинье
PUT http://localhost:8080/users/like/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### После лгина вставить токен после слова "Bearer" и посмотреть кого мы лайкнули
GET http://localhost:8080/users/welike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### После лгина вставить токен после слова "Bearer" и посмотреть сударей
GET http://localhost:8080/users/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### true
GET http://localhost:8080/users/reciprocity/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### false
GET http://localhost:8080/users/reciprocity/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### true
GET http://localhost:8080/users/exists/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

### false
GET http://localhost:8080/users/exists/99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhIiwiZXhwIjoxNjQ4ODIxNDYzLCJpYXQiOjE2NDg4MDM0NjN9.NoPWB9XZ9bQ5Bn5sLp6AL7XdpRLXsY6r2L8GBItVX4bDxU32rW1uLJ3umfsLWfsdB93B0NNOU69mWpoSMCUZ1A

###
GET http://localhost:8080/users/reciprocity
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw

###
GET http://localhost:8080/users/likers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTY0ODkyNzU4MSwiaWF0IjoxNjQ4OTA5NTgxfQ.O9sjEsqYqLlpMFRFGuxoVi5AQ9rDnia8MStyD2Y5YD7n6-sQRTxV6sKwbCMXEakoZ3FpUglKjakpuV63RZLOiw
