telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://bd70-5-149-159-44.ngrok.io"
  bot-name: "LigaTinderBot"
  bot-token: "5283237136:AAHtqzNjyNz5VMNadJHWyACQIk004n3MBps"

server:
  port: "5000"

localeTag: ru-RU

upload:
  #Rob_Linux
  path: /home/robert/IdeaProjects/Jtinder/Client/src/main/resources/prerev-background.jpg

  #Docker_Linux
  #path: /home/jtinder/src/main/resources/prerev-background.jpg

  #Alex_Windows
  #path: E:\Java\Jtinder\Client\src\main\resources\prerev-background.jpg

key:
  localPath: "http://localhost:8080/"